name:  Reporte de Bug
description: Crear un reporte de bug para ayudar a mejorar Cryptic
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por reportar un bug. Por favor completa toda la informaci贸n posible para ayudar a reproducir y solucionar el problema.

  - type: textarea
    id: descripcion
    attributes:
      label: Descripci贸n del problema
      description: Una descripci贸n clara y concisa del bug encontrado.
      placeholder: Describe qu茅 sucede y qu茅 esperabas que ocurriera.
    validations:
      required: true

  - type: textarea
    id: pasos
    attributes:
      label: Pasos para reproducir
      description: Lista los pasos exactos para reproducir el problema.
      placeholder: |
        1. Ejecut茅 el comando '...'
        2. Seleccion茅 la opci贸n '...'
        3. Apareci贸 el error '...'
    validations:
      required: true

  - type: textarea
    id: comportamiento_esperado
    attributes:
      label: Comportamiento esperado
      description: Describe qu茅 deber铆a ocurrir normalmente.
      placeholder: El programa deber铆a mostrar el resultado correcto sin errores.

  - type: textarea
    id: comportamiento_actual
    attributes:
      label: Comportamiento actual
      description: Describe exactamente qu茅 ocurre (incluye mensajes de error si los hay).
      placeholder: Aparece el mensaje de error "..." y el programa se cierra.

  - type: textarea
    id: datos_prueba
    attributes:
      label: Datos de prueba
      description: Proporciona datos de ejemplo que reproduzcan el problema (sin informaci贸n sensible real).
      placeholder: |
        Input: "ejemplo@dominio.com"
        Output esperado: "Email detectado correctamente"
        Output actual: "Error inesperado"

  - type: dropdown
    id: version
    attributes:
      label: Versi贸n de Cryptic
      description: 驴Qu茅 versi贸n de Cryptic est谩s usando?
      options:
        - 0.1.0 (煤ltima)
        - 0.0.x (desarrollo)
        - Otra (especificar abajo)
    validations:
      required: true

  - type: dropdown
    id: python_version
    attributes:
      label: Versi贸n de Python
      description: 驴Qu茅 versi贸n de Python est谩s usando?
      options:
        - Python 3.12
        - Python 3.11
        - Python 3.10
        - Python 3.9
        - Python 3.8
        - Otra
    validations:
      required: true

  - type: dropdown
    id: sistema_operativo
    attributes:
      label: Sistema operativo
      description: 驴En qu茅 sistema operativo ocurre el problema?
      options:
        - Linux
        - macOS
        - Windows
        - Otro
    validations:
      required: true

  - type: textarea
    id: contexto_adicional
    attributes:
      label: Informaci贸n adicional
      description: Cualquier informaci贸n adicional que pueda ayudar a solucionar el problema.
      placeholder: Logs, configuraci贸n espec铆fica, entorno de desarrollo, etc.
